allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - brace-expansion@5.0.8
overrides:
  brace-expansion@<=5.0.7: ^5.0.8
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
