allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - yaml@2.8.3
  - devalue@5.8.1
overrides:
  devalue@>=5.6.3 <=5.8.0: ^5.8.1
  yaml@>=2.0.0 <2.8.3: ^2.8.3
publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
